#cloud-config                     
users:                             # Benutzer
  - name: ubuntu                   # Nutzername
    groups: [users, admin]         # Gruppen
    shell: /bin/bash               # Shell
    sudo: ALL=(ALL) NOPASSWD:ALL   # Passwortloses sudo
    ssh_authorized_keys:           # SSH-Keys
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBHPGqRE3fund31MUFowXo5aDYBiMjgpI12teC//csiLM32MCgqZPvlSvWokiGPDubpBsI/HjoqxZxjOWGxEQzskD7YzpH3LLNewSZCVzkz2cgXS3+zSwkgb9Al9s21/vIQpHIHXZyRHeab+NqjvCD51zPeBTUzSNewYtTc6hiI34pGbts67ushHRwV9mwNxIFngSSI9HL1m6kq37WnIPubJKSk/XLWLSN1T1nmL+FiKbypSf7hi2vKQ9Cf2E0iVphGIxP2GYYnEZ7Gc6oFiOQnulLQlBNxU8VXDzAmKMVchFRpQVTOh+DfiXNg2c3hw2kWP6LgrJHu6hMod5ekM6z aws-key # Ã–ffentlicher SSH-Key

ssh_pwauth: false                  # Kein Passwort-Login
disable_root: false                # Root erlaubt
package_update: true               # apt update
packages:                          # Pakete installieren
  - curl                           # curl
  - wget                           # wget
